//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MocauManagementDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMLicenceDevEntities : DbContext
    {
        public PMLicenceDevEntities()
            : base("metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=System.Data.SqlClient;provider connection string='data source=14.161.20.180;initial catalog=PMLicenceDev;user id=mocau;password=MOCAU2016;MultipleActiveResultSets=True;App=EntityFramework;'")
        {
        }

        //private string GetConnectionString()
        //{
        //    return @"metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=14.161.20.180;initial catalog=PMLicenceDev;user id=mocau;password=MOCAU2016;MultipleActiveResultSets=True;App=EntityFramework&quot;";
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PMLicenceKey> PMLicenceKeys { get; set; }
        public virtual DbSet<PMLicenceKeyHi> PMLicenceKeyHis { get; set; }
    }
}
