//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MocauManagementDAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class PMLicenceKeyHi
    {
        [Key]
        [Column(Order = 1)]
        public string HWKey { get; set; }
        [Key]
        [Column(Order = 2)]
        public string PublicKey { get; set; }
        public string PrivateKey { get; set; }
        public System.DateTime ActivedDate { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string SoftwareVersion { get; set; }
        public string PCName { get; set; }
    
        public virtual PMLicenceKey PMLicenceKey { get; set; }
    }
}
